# Generated by Django 3.2.7 on 2021-12-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
