# Generated by Django 3.2.7 on 2021-12-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationuser_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationUser',
        ),
    ]
